# Get all books
GET http://localhost:8081/books HTTP/1.1
Content-Type: application/json

###

# Create a book
POST http://localhost:8081/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter",
  "imgUrl": "https://m.media-amazon.com/images/I/71HbYElfY0L._AC_UF1000,1000_QL80_.jpg"
}

###

# Update a book
PUT http://localhost:8081/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower",
  "imgUrl": "https://upload.wikimedia.org/wikipedia/en/5/54/Thedarktower7.jpg"
}

###

# Delete a book
DELETE http://localhost:8081/books/1 HTTP/1.1
Content-Type: application/json