version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=devops
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local