services:
  # ======================
  # Database (PostgreSQL 18.1)
  # ======================
  database:
    container_name: database-ctr
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: devops
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql -d devops"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
